# Colors (LuciusDarkHighContrast)
colors:
  # Default colors
  primary:
    background: '#303030'
    foreground: '#eeeeee'

  # Cursor colors
  cursor:
    text: '#303030'
    cursor: '#afd7ff'

  # Normal colors
  normal:
    black:   '#303030'
    red:     '#ff8787'
    green:   '#d7ffaf'
    yellow:  '#ffffd7'
    blue:    '#afffff'
    magenta: '#ffd7ff'
    cyan:    '#afffd7'
    white:   '#eeeeee'

  # Bright colors
  bright:
    black:   '#303030'
    red:     '#ff8787'
    green:   '#d7ffaf'
    yellow:  '#ffffd7'
    blue:    '#afffff'
    magenta: '#ffd7ff'
    cyan:    '#afffd7'
    white:   '#eeeeee'
font:
  italic:
    family: 'Hack Nerd Font Mono'
    style: 'Italic'
  bold:
    family: 'Hack Nerd Font Mono'
    style: 'Bold'
  normal:
    family: 'Hack Nerd Font Mono'
key_bindings:
  - { key: Q, mods: Control, chars: "\x11" }
  - { key: Slash, mods: Control, chars: "\x1f" }

  - { mods: Alt, key: A, chars: "\x1ba" }
  - { mods: Alt, key: B, chars: "\x1bb" }
  - { mods: Alt, key: C, chars: "\x1bc" }
  - { mods: Alt, key: D, chars: "\x1bd" }
  - { mods: Alt, key: E, chars: "\x1be" }
  - { mods: Alt, key: F, chars: "\x1bf" }
  - { mods: Alt, key: G, chars: "\x1bg" }
  - { mods: Alt, key: H, chars: "\x1bh" }
  - { mods: Alt, key: I, chars: "\x1bi" }
  - { mods: Alt, key: J, chars: "\x1bj" }
  - { mods: Alt, key: K, chars: "\x1bK" }
  - { mods: Alt, key: L, chars: "\x1bl" }
  - { mods: Alt, key: M, chars: "\x1bm" }
  - { mods: Alt, key: N, chars: "\x1bn" }
  - { mods: Alt, key: O, chars: "\x1bo" }
  - { mods: Alt, key: P, chars: "\x1bp" }
  - { mods: Alt, key: Q, chars: "\x1bq" }
  - { mods: Alt, key: R, chars: "\x1br" }
  - { mods: Alt, key: S, chars: "\x1bs" }
  - { mods: Alt, key: T, chars: "\x1bt" }
  - { mods: Alt, key: U, chars: "\x1bu" }
  - { mods: Alt, key: V, chars: "\x1bv" }
  - { mods: Alt, key: W, chars: "\x1bw" }
  - { mods: Alt, key: X, chars: "\x1bx" }
  - { mods: Alt, key: Y, chars: "\x1by" }
  - { mods: Alt, key: Z, chars: "\x1bz" }
  - { mods: Alt, key: Slash, chars: "\x1b/" }
